### ISSUE TITLE
Default distribution/vendor should be configurable

### ISSUE THREAD

**Issue by marcphilipp** [gradle/foojay-toolchains#11]
As documented [in the README](https://github.com/gradle/foojay-toolchains#vendors), the default distribution is currently Temurin if no vendor is specified. Since Temurin does not provide an arm64-compatible JDK 8 distribution, projects like JUnit have to explicitly specify a vendor when using JDK 8 even though any vendor would do. Therefore, it would be great if the default vendor could be configured, e.g. via a DSL in the settings script or a project/system property.

**Comment by leonard84** [comment]
Alternatively, you could support fallback vendors, that are tried when the default vendor doesn't supply a JDK matching the other criteria.
