### ISSUE TITLE
option to install a x86-64 JDK on an m1 mac because it can run with Rosetta 2

### ISSUE THREAD

**Issue by reinsch82** [gradle/foojay-toolchains#17]
When using the toolchain declaration and there is no JDK for the aarch64 architecture available on a mac. there should be an option to also allow usage of a x86-64 JDK since [Rosetta 2](https://en.wikipedia.org/wiki/Rosetta_(software)#Rosetta_2) allows it to execute.

### Expected Behavior
some way of configuring to allow x86-64

### Current Behavior
older JDKs can't be used on m1 macs

**Comment by joshfriend** [comment]
How old of a JDK do you need? Azul has Zulu builds of 1.8 for aarch64 macs

**Comment by gudenau** [comment]
This could be nice on Linux as well. There is support in the kernel for running non-native binaries through something like qemu.
