### ISSUE TITLE
Release first version to the Prod Portal

### ISSUE THREAD

**Issue by jbartok** [gradle/foojay-toolchains#2]

**Comment by sschuberth** [comment]
Probably update [this](https://github.com/gradle/foojay-toolchains/blob/b31b480dee2c17e7a0bd4c5a1eac18d9a8b4937f/gradle/wrapper/gradle-wrapper.properties#L3) to 7.6 final first 😀

**Comment by sschuberth** [comment]
> Probably update [this](https://github.com/gradle/foojay-toolchains/blob/b31b480dee2c17e7a0bd4c5a1eac18d9a8b4937f/gradle/wrapper/gradle-wrapper.properties#L3) to 7.6 final first 😀

I've created a PR: https://github.com/gradle/foojay-toolchains/pull/4

**Comment by jbartok** [comment]
https://plugins.gradle.org/plugin/org.gradle.toolchains.foojay-resolver
https://plugins.gradle.org/plugin/org.gradle.toolchains.foojay-resolver-convention

**Comment by sschuberth** [comment]
Is it correct to *not* use `*-convention` in `classpath` below?

![image](https://user-images.githubusercontent.com/349154/204268847-676e485f-dcf8-4aa7-9833-3e342d90deea.png)
