### ISSUE TITLE
Gradle corrupt after add this plugin

### ISSUE THREAD

**Issue by shoulder0902** [gradle/foojay-toolchains#21]
As below:
> org.gradle.api.internal.project.DefaultProject_Decorated cannot be cast to org.gradle.api.initialization.Settings
> org.gradle.api.internal.project.DefaultProject_Decorated cannot be cast to org.gradle.api.initialization.Settings
> 
> Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
> 
> Re-download dependencies and sync project (requires network)
> The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
> 
> Stop Gradle build processes (requires restart)
> Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.
> 
> In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

I tried the methods mentioned above:
1. Re-download dependencies and sync project
2. Stop Gradle build processes
And:
3. kill Gradle daemon, delete the Gradle caches
4. I use the Gradle 8+, so I create a new project with basic configured Gradle 7.4.2 and add this plugin.

The problem appeared again.

**Comment by TheNaqvi** [comment]
Same problem for me with gradle 8.0.1

**Comment by jbartok** [comment]
The plugin is compatible with Gradle 7.6 or newer only.
What do you mean by `I use the Gradle 8+, so I create a new project with basic configured Gradle 7.4.2 and add this plugin.`? If you use `Gradle 7.4.2`, then it's expected to fail. 
If you are using `Gradle 8+`, pls. create an issue with a reproducer on the [`gradle/gradle`](https://github.com/gradle/gradle) repo.
Or re-open this issue, but provide a bit more info, so I can reproduce the problem.

**Comment by zameelpichen** [comment]
I am having the same issue

android_gradle_plugin = 8.0.0
gradleversion = 8.1

![image](https://user-images.githubusercontent.com/25373198/234038489-e5e666aa-d983-4006-8cc7-444a582b9c2f.png)


following is my root build.gradle.kts file
```

plugins {
    alias(libs.plugins.dependencyanalysis)
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.5.0"

}

buildscript {
    repositories {
        mavenCentral()
        google()
        gradlePluginPortal()
    }
    dependencies {
        classpath(libs.android.gradle.plugin)
        classpath(libs.kotlin.gradle.plugin)
        classpath(libs.aboutlibraries.plugin)
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
```

Note : I maybe missing something obvious here.
Thanks in advance.
