### ISSUE TITLE
Proposal: Remove foojay from plugin id as this expose implementation details 

### ISSUE THREAD

**Issue by StefMa** [gradle/foojay-toolchains#23]
Hi guys,

I just read a bit about this plugin, what it does and what it offers etc.
While looking at it, I kept wondering why it's called "foojay".
Well, it makes sense because it uses the foojay api under the hood. Fine.
But thinking a bit further, I think it makes sense to remove this information from the ID as it is not needed. Why should an implementation be exposed to something "generic" like a toolchain vendor?
Just thinking about the future. Imagine you change your API provider. For whatever reason. Will you create a new repository? Will you create a new plugin? Will you keep the foojay name but change the api?

I think to make this plugin more future proof it would make sense to at least remove the foojay information from the plugin id so you can change the jdk provider as you like in the future...

What do you think?

**Comment by jbartok** [comment]
I appreciate your interest in this plugin. However, I must disagree.
This plugin is *one of many possible* Gradle [Toolchain Resolver Plugins](https://docs.gradle.org/current/userguide/toolchain_plugins.html#toolchain_plugins), which is specifically based on the DiscoAPI provided by Foojay. 
If it would be based on something else, then that would be another such plugin and would be named accordingly.
It's specific, with a specific name. 
That doesn't make it non-future-proof.
