### ISSUE TITLE
Double-check GraalVM support

### ISSUE THREAD

**Issue by sschuberth** [gradle/foojay-toolchains#3]
The README currently says:

> GraalVM distributions just don't seem to work in the current version of the DiscoAPI, so this version of the plugin doesn't map to them.

But [this](https://github.com/foojayio/discoapi/issues/51) discoapi issue suggests that it's supported.

**Comment by jbartok** [comment]
@sschuberth something is not right with the GraalVM support. When you attempt to fetch packages for those distributions you just get a huge list of packages from other distributions. Try for example: 

`curl -X 'GET' 'https://api.foojay.io/disco/v3.0/packages?version=11&distro=Graal+VM+CE+11&latest=available&directly_downloadable=true&package_type=jdk' -H 'accept: application/json'`

**Comment by sschuberth** [comment]
@jbartok that query of yours is using the wrong name for the `distro`, which is what I was trying to hint at initially. However, also https://api.foojay.io/disco/v3.0/packages?distro=graalvm_ce11 does not work, though in a different way: It says "No package(s) found". I've [asked](https://github.com/foojayio/discoapi/issues/51#issuecomment-1326290169) about that.

**Comment by jbartok** [comment]
It's not the wrong name per se, but it's the `name` and not the `api_parameter` value, which is maybe what I should be using. Also asked them, let's see what they come back with. Thanks!

**Comment by sschuberth** [comment]
Can we reopen this now that https://github.com/foojayio/discoapi/issues/51 was fixed and add GraalVM support to the plugin @jbartok?

**Comment by jbartok** [comment]
Did reopen it and started working on GraalVM support in the plugin, but found another issue: https://github.com/foojayio/discoapi/issues/66

I'll continue when they fix it (almost finished).

**Comment by jbartok** [comment]
Done.
