### ISSUE TITLE
Support new GraalVM releases

### ISSUE THREAD

**Issue by sschuberth** [gradle/foojay-toolchains#31]
The new GraalVM release [changed the versioning scheme](https://medium.com/graalvm/a-new-graalvm-release-and-new-free-license-4aab483692f5#8822) to be aligned with the JDK version. To reflect this in a non-conflicting manner, *discoapi* uses the [new name](https://github.com/foojayio/discoapi/issues/75) "graalvm_community" (and "graal" for the new "Oracle GraalVM" distribution under the [GraalVM Free Terms and Conditions (GFTC) license](https://www.oracle.com/downloads/licenses/graal-free-license.html)).

As currently the GraalVM Community Edition name is assumed to be "GraalVM CE *X*" where *X* is an integer, this change in the version / name requires some adjustments to this plugin as well.

Here are example responses from the *discoapi* [distributions](https://api.foojay.io/swagger-ui#/default/getDistributionsV3) API call:

```
    {
      "name": "GraalVM",
      "api_parameter": "graalvm",
      "maintained": true,
      "build_of_openjdk": false,
      "build_of_graalvm": true,
      "official_uri": "https://www.graalvm.org/",
      "synonyms": [
        "graalvm",
        "GRAALVM",
        "GraalVM"
      ],
      "versions": [
        "20.0.1",
        "17.0.7"
      ]
    }
```

```
    {
      "name": "GraalVM Community",
      "api_parameter": "graalvm_community",
      "maintained": true,
      "build_of_openjdk": false,
      "build_of_graalvm": true,
      "official_uri": "https://www.graalvm.org/",
      "synonyms": [
        "graalvm_community",
        "GRAALVM_COMMUNITY",
        "GraalVM Community",
        "graalvm community"
      ],
      "versions": [
        "20.0.1",
        "17.0.7"
      ]
    }
```

```
    {
      "name": "GraalVM CE 8",
      "api_parameter": "graalvm_ce8",
      "maintained": false,
      "build_of_openjdk": false,
      "build_of_graalvm": true,
      "official_uri": "https://www.graalvm.org/",
      "synonyms": [
        "graalvm_ce8",
        "graalvmce8",
        "GraalVM CE 8",
        "GraalVMCE8",
        "GraalVM_CE8"
      ],
      "versions": [
        "21.3.1",
        "21.2",
        "21.1",
        "21.0.0.2",
        "21",
        "20.3.3",
        "20.3.2",
        "20.3.1.2",
        "20.3.1",
        "20.3",
        "20.2",
        "20.1",
        "20-ea",
        "19.3.6",
        "19.3.5",
        "19.3.4",
        "19.3.3",
        "19.3.2",
        "19.3.1",
        "19.3.0.2",
        "19.3"
      ]
    }
```

**Comment by sschuberth** [comment]
Note, the [graalvm-community-openjdk-20.0.1+9.1](https://github.com/graalvm/graalvm-ce-builds/releases/tag/jdk-20.0.1) distribution has `java.vendor = GraalVM Community` whereas [Oracle GraalVM](https://www.graalvm.org/downloads/) has `java.vendor = Oracle Corporation`.

**Comment by sschuberth** [comment]
> Feel free to reach out to me, happy to help.

@fniephaus, could you help me understand the (by now) "legacy" GraalVM versioning scheme?

Like, e.g. in "GraalVM CE 17" what does the "17" stand for? Is that the Java language level, i.e. Java 17? And if so, why is [there](https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-22.3.2) also a parallel "GraalVM CE 11" release if a Java 17 compiler usually can also target Java 11? I.e. what sense does it make to release "GraalVM CE 11" *and* "GraalVM CE 17" at the *same time*? Finally, what's 22.3.2 in above's example? The GraalVM release version that's basically independent of the java language version?

Thanks for any insights!

**Comment by fniephaus** [comment]
> Like, e.g. in "GraalVM CE 17" what does the "17" stand for? Is that the Java language level, i.e. Java 17?

Yes, that is correct.

> And if so, why is [there](https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-22.3.2) also a parallel "GraalVM CE 11" release if a Java 17 compiler usually can also target Java 11

Previous GraalVM releases, although built from the same GraalVM sources (e.g. `22.3.0`), targeted multiple Java versions. `22.3.0`, for example, includes builds for Java 11, 17, and 19.

> Finally, what's 22.3.2 in above's example? The GraalVM release version that's basically independent of the java language version?

That's the GraalVM version, which we currently still use to version the GraalVM sources.

Fun fact: technically, GraalVM for JDK 17 and JDK 20 were also built from the same sources (`23.0.0`). Due to the OpenJDK alignment, however, we've adjusted the versioning scheme so that it no longer includes the GraalVM source version (`23.0.0`). Instead, GraalVM releases will follow the OpenJDK release calendar. So in September, there is going to be a GraalVM for JDK 21 release.

**Comment by sschuberth** [comment]
This is blocked by https://github.com/foojayio/discoapi/issues/77.

**Comment by tanvirp** [comment]
> This is blocked by [foojayio/discoapi#77](https://github.com/foojayio/discoapi/issues/77).

The above issue is already closed as invalid. What does that mean for this issue?

**Comment by sschuberth** [comment]
> > This is blocked by [foojayio/discoapi#77](https://github.com/foojayio/discoapi/issues/77).
> 
> The above issue is already closed as invalid. What does that mean for this issue?

It's not blocked anymore. That's why I've created https://github.com/gradle/foojay-toolchains/pull/35 to resolve this issue.
