### ISSUE TITLE
Please maintain a changelog or GitHub releases

### ISSUE THREAD

**Issue by gabrielfeo** [gradle/foojay-toolchains#67]
It's important for developers to review changes coming in whenever a dependency is updated, and for that we rely on changelogs to avoid the burden of reviewing a full git log and diff. But currently, the repo has no `CHANGELOG.md` file and GH releases are not published with a description.

**Comment by ov7a** [comment]
Would the plugin portal page of the plugin work for you?
https://plugins.gradle.org/plugin/org.gradle.toolchains.foojay-resolver

**Comment by gabrielfeo** [comment]
Publishing a changelog or GH releases would play nicer with automations (Dependabot, etc.), but yes. Out of curiosity where does that changelog in the Portal come from?

**Comment by ov7a** [comment]
> Publishing a changelog or GH releases would play nicer with automations (Dependabot, etc.), but yes. 

I agree.

> Out of curiosity, where does that changelog in the Portal come from?

https://github.com/gradle/foojay-toolchains/blob/main/foojay-resolver/release-notes-0.8.0.txt and similar files, see the git history of the folder
