### ISSUE TITLE
Gradle 8.10: Failed to transform foojay-resolver-0.8.0.jar

### ISSUE THREAD

**Issue by kriadov** [gradle/foojay-toolchains#75]
`What went wrong: 
Could not resolve all artifacts for configuration 'classpath'.
> Failed to transform foojay-resolver-0.8.0.jar (org.gradle.toolchains:foojay-resolver:0.8.0) to match attributes {artifactType=jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.internal.instrumented=instrumented-and-upgraded, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
   > Execution failed for MergeInstrumentationAnalysisTransform: /Users/kriadov/.gradle/caches/8.10/transforms/daf5de6db9916bbe067863100123e70b/transformed/analysis/instrumentation-dependencies.bin.
      > com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Could not deserialize analysis from a file: /Users/kriadov/.gradle/caches/8.10/transforms/daf5de6db9916bbe067863100123e70b/transformed/analysis/instrumentation-hierarchy.bin`

**Comment by jbartok** [comment]
Insufficient information to address.
